Login page
LinkUpFiuba/web pull request #1
Opened 2017-09-22 21:34 UTC by fedebrasburg

2017-09-25 03:43 UTC, pciruzzi requested changes
Acordate de darme acceso al Heroku de esto después

2017-09-25 03:43 UTC, pciruzzi commented on config/jest/cssTransform.js
> +'use strict';
En el laburo usamos `glamor` para lo que es `css`. Lo que te permite es tener todo en un mismo archivo (El componente y el `css`). Por si queremos tenerlo en cuenta...

2017-09-25 03:43 UTC, pciruzzi commented on package-lock.json
>        "resolved": "https://registry.npmjs.org/abab/-/abab-1.0.3.tgz",
Todo este archivo debería volar, no?

2017-09-25 03:43 UTC, pciruzzi commented on package.json
> +    "autoprefixer": "7.1.2",
Posta necesitamos todas estas dependencias? jajaja

2017-09-25 03:43 UTC, pciruzzi commented on package.json
> +  "lint-staged": {
No se usa `eslint` como linter?

2017-09-25 03:43 UTC, pciruzzi commented on src/Components/LinkUpLogo.js
> +class LinkUpLogo extends Component {
Podríamos pedir el logo en mejor definición, no?

2017-09-25 03:43 UTC, pciruzzi commented on src/Pages/UsersListPage/UsersListPage.js
> +    return <h1> Lista</h1>;
Hay un espacio de más en el texto

2017-09-25 03:43 UTC, pciruzzi commented on src/index.css
> +    background-color: #B52F5A;
Este es el mismo color que se usa en la app?

2017-09-25 03:43 UTC, pciruzzi commented on src/Pages/LoginPage/LoginPage.js
> +          <h1> Link Up </h1>
Hay espacios de más en el texto

2017-09-25 03:43 UTC, pciruzzi commented on src/App.js
>  import React, { Component } from 'react';
Fijate que en todo `src` hay varios `;` de más 😄

2017-09-25 03:43 UTC, pciruzzi commented on src/App.js
> +          onClick={() => {
Esta función podría estar afuera así queda más prolijo y ponés todo el `<button>` en el mismo renglón

2017-09-25 03:43 UTC, pciruzzi commented on src/App.js
> +        Welcome!
Inglés?

2017-09-25 03:43 UTC, pciruzzi commented on src/Components/FullNavBar.js
> +class FullNavBar extends Component {
Esto dónde se usa? 🤔

2017-09-25 03:43 UTC, pciruzzi commented on README.md
> -This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app).
Fijate de escribirle un mini `README` al menos de cómo arrancarlo, etc

2017-09-26 18:02 UTC, fedebrasburg commented
![](https://github.trello.services/images/mini-trello-icon.png) [(13) Como administrador quiero poder acceder a una plataforma web para gestionar el contenido de la aplicación](https://trello.com/c/Cqvztd72/10-13-como-administrador-quiero-poder-acceder-a-una-plataforma-web-para-gestionar-el-contenido-de-la-aplicaci%C3%B3n)

2017-09-26 18:44 UTC, fedebrasburg commented on config/jest/cssTransform.js
> +'use strict';
Entiendo, pero para mi es mas claro tenerlos por separado. Uso css modules (para eso hice el `eject`)

2017-09-26 18:44 UTC, fedebrasburg commented on package-lock.json
>        "resolved": "https://registry.npmjs.org/abab/-/abab-1.0.3.tgz",
si

2017-09-26 18:45 UTC, fedebrasburg commented on package.json
> +    "autoprefixer": "7.1.2",
Parece que si, las puso el `eject`

2017-09-26 18:46 UTC, fedebrasburg commented on package.json
> +  "lint-staged": {
Uso prettier

2017-09-26 18:46 UTC, fedebrasburg commented on src/Components/LinkUpLogo.js
> +class LinkUpLogo extends Component {
Pedi el mejor que tenían jaja hay que pedir mas

2017-09-26 18:46 UTC, fedebrasburg commented on src/index.css
> +    background-color: #B52F5A;
Sisi

2017-09-26 18:49 UTC, fedebrasburg commented on src/Pages/LoginPage/LoginPage.js
> +          <h1> Link Up </h1>
👍

2017-09-26 18:50 UTC, fedebrasburg commented on src/App.js
>  import React, { Component } from 'react';
👍

2017-09-26 18:50 UTC, fedebrasburg commented on src/App.js
> +        Welcome!
Es provisorio, esta pagina va a cambiar en un proximo PR

2017-09-26 18:51 UTC, fedebrasburg commented on src/Components/FullNavBar.js
> +class FullNavBar extends Component {
En ningún lugar aun

2017-09-26 18:51 UTC, fedebrasburg commented on README.md
> -This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app).
Dale

2017-09-26 18:53 UTC, fedebrasburg commented on src/App.js
> +          onClick={() => {
No puedo por que necesita el history de parámetro, igualmente esto se va a ir en un proximo PR

2017-09-27 01:15 UTC, pciruzzi reviewed
Fijate que quedaron comentarios anteriores, como borrar el `package-lock` (Tendrías que sacarlo del `.gitignore`, borrarlo, commitear y volver a agregarlo al `.gitignore`), algún espacio de más, los `;` en la carpeta `src`, etc

2017-09-27 01:15 UTC, pciruzzi commented on src/App.js
> +// It will vee deleted in the next commit
Anda a saber qué estabas pensando cuando escribiste el `vee` no? jajajaj

2017-09-27 01:15 UTC, pciruzzi commented on src/Constants.js
> +export const adminPass = 'admin';
Security level god

2017-09-27 01:30 UTC, fedebrasburg commented on src/Constants.js
> +export const adminPass = 'admin';
:godmode:

2017-09-27 01:31 UTC, fedebrasburg commented on src/App.js
> +// It will vee deleted in the next commit
`nice`

2017-09-27 02:14 UTC, pciruzzi approved these changes
No sé si te faltó un commit porque en el de "delete ;" no se borra ningún ; justamente, pero bueno. De todas formas habría que volarlos si vamos a usar ES6... y de paso cambiate el color ese a `#E00051` que es el que extraje de los mockups :)

Si querés hacelo en otro PR, pero para que esté digo

2017-09-27 03:45 UTC, fedebrasburg commented
Ya se lo que pasa, cuando hace el pre commit, agrega todos los ;

2017-09-27 03:54 UTC, merged